name: Daily Auto Commit

on:
  schedule:
    # Runs daily at 04:30 AM UTC (10:00 AM IST)
    - cron: "30 4 * * *"
  workflow_dispatch: # Allows manual execution

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add timestamp (by 23f2005701@ds.study.iitm.ac.in)
        run: |
          echo "Last updated on $(date -u)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add daily-log.txt
          git commit -m "Daily auto-update: $(date -u)" || exit 0
          git push
